### ISSUE TITLE
There are many way of getting cell phone location

### ISSUE THREAD

**Issue by nhanth87** [RestComm/gmlc#9] opened 2016-01-28 17:50 UTC
Can we implement all the thing in this document:
https://events.ccc.de/congress/2014/Fahrplan/system/attachments/2553/original/31c3-ss7-locate-track-manipulate.pdf

**Comment by FerUy** [comment] 2016-08-01 17:49
This is a duplicate of what's covered in #1 and #2. Good research, thanks for the doc @nhanth87

**Closed as completed by FerUy** 2016-08-01 17:49 UTC
